remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
theme: jekyll-theme-cayman
title: The role of women in the film industry - what is behind the prejudices?
description: We shed light on the truth about gender equity in the film industry by analysing over 42000 movies
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Role of women in film industry
    url: website
  - title: Example
    url: example
  - title: Part 2 - Semantic analysis
    url: website_part2
