remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
theme: jekyll-theme-cayman
title: The role of women in the film industry - what is behind the prejudices?
description: We shed light on the truth about gender equity in the film industry by analysing over 42'000 movies.
show_downloads: True
navigation:
  - title: Introduction and preliminary analyses
    url: Intro
  - title: Part 1 - Quantitative analysis
    url: website
  - title: Part 2 - Qualitative analysis
    url: website_part2

